<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" autocomplete="off">
<fieldset>
	<?php if (count($this->element->getErrorMessages())): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->getErrorMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="email"><?php echo $this->element->email->getLabel(); ?>:</label>
		<input type="email" id="email" name="<?php echo $this->element->email->getName(); ?>" value="<?php echo $this->element->email->getValue(); ?>" maxlength="128" required="required">
		<?php if (count($this->element->email->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->email->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<label for="login"><?php echo $this->element->login->getLabel(); ?>:</label>
		<input type="text" id="login" name="<?php echo $this->element->login->getName(); ?>" value="<?php echo $this->element->login->getValue(); ?>" maxlength="30" required="required">
		<?php if (count($this->element->login->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->login->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<label for="password"><?php echo $this->element->password->getLabel(); ?>:</label>
		<input type="password" id="password" name="<?php echo $this->element->password->getName(); ?>" required="required">
		<?php if (count($this->element->password->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->password->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<label for="passwordconfirm"><?php echo $this->element->passwordconfirm->getLabel(); ?>:</label>
		<input type="password" id="passwordconfirm" name="<?php echo $this->element->passwordconfirm->getName(); ?>" required="required">
		<?php if (count($this->element->passwordconfirm->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->passwordconfirm->getMessages()) . '.', '.'); ?></span>
		<?php endif; ?>
	</p>
	<p>
		<button class="button" type="submit">Utwórz nowe konto</button>
	</p>
</fieldset>
</form>
