<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>">
	<p>
		<label for="email">E-mail:</label>
		<input type="email" id="email" name="<?php echo $this->element->email->getName(); ?>">
		<?php if (count($this->element->email->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->email->getMessages()) . '.', '.'); ?></span>
		<?php endif;?>
	</p>
	<p>
		<label for="password">Hasło:</label>
		<input type="password" id="password" name="<?php echo $this->element->password->getName(); ?>">
		<?php if (count($this->element->password->getMessages()) > 0): ?>
		<span class="error"><?php echo ltrim(implode('. ', $this->element->password->getMessages()) . '.', '.'); ?></span>
		<?php endif;?>
	</p>
	<p>
		<button class="button" type="submit">Zaloguj się</button>
	</p>
</form>
