<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>">
<fieldset>
	<?php if (count($this->element->email->getMessages()) > 0): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->email->getMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="email">E-mail:</label>
		<input type="email" id="email" name="email">
	</p>
	<?php if (count($this->element->login->getMessages()) > 0): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->login->getMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="login">Login na Blip:</label>
		<input type="text" id="login" name="login">
	</p>
	<?php if (count($this->element->password->getMessages()) > 0): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->password->getMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="password">Hasło:</label>
		<input type="password" id="password" name="password">
	</p>
	<?php if (count($this->element->passwordconfirm->getMessages()) > 0): ?>
	<p class="error"><?php echo ltrim(implode('. ', $this->element->passwordconfirm->getMessages()) . '.', '.'); ?></p>
	<?php endif; ?>
	<p>
		<label for="passwordconfirm">Powtórz hasło:</label>
		<input type="password" id="passwordconfirm" name="passwordconfirm">
	</p>
	<p>
		<button class="button" type="submit">Utwórz nowe konto</button>
	</p>
</fieldset>
</form>
