<nav>
	<ul>
		<li><a class="button pillbox pillbox-l shad0w selected" href="<?php echo $this->url(array(), 'index') ?>">Strona główna</a></li>
		<li><a class="button pillbox pillbox-m shad0w f" href="<?php echo $this->url(array(), 'index') ?>">Zamówienia <?php if ($this->bookRequestNumber) echo '(' . $this->bookRequestNumber . ')'; ?></a></li>
		<li><a class="button pillbox pillbox-m shad0w f" href="<?php echo $this->url(array(), 'index') ?>">Twoje książki</a></li>
		<li><a class="button pillbox pillbox-m shad0w " href="<?php echo $this->url(array(), 'index') ?>">Kurierzy i kursy</a></li>
		<li><a class="button pillbox pillbox-r shad0w " href="<?php echo $this->url(array(), 'index') ?>">Dodaj książkę…</a></li>
	</ul>
</nav>


