<h2>License</h2>

<p>All Blipoteka code is a Free Software and is distributed (unless otherwise stated) on terms
of Simplified BSD License:</p>

<h3>Simplified BSD License</h3>

<pre>
Copyright 2010-2011 Blipoteka.pl. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are
permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice, this list of
      conditions and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright notice, this list
      of conditions and the following disclaimer in the documentation and/or other materials
      provided with the distribution.

THIS SOFTWARE IS PROVIDED BY Blipoteka.pl ``AS IS'' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Blipoteka.pl OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those of the
authors and should not be interpreted as representing official policies, either expressed
or implied, of Blipoteka.pl.
</pre>

<p>Blipoteka.pl makes use of other pieces of Free Software:</p>

<h3>Other licenses</h3>

<ul>
	<li><a href="http://960.gs">960.gs</a> (MIT license)</li>
	<li><a href="http://html5boilerplate.com/">HTML5 Boilerplate</a> (MIT, BSD, Public Domain)</li>
	<li><a href="http://code.google.com/p/blipapi/">BlipApi</a> (GNU LGPL)</li>
	<li><a href="http://www.doctrine-project.org/">Doctrine</a> (GNU LGPL)</li>
</ul>

<h3>Web fonts</h3>

<p>Blipoteka.pl uses GraublauWeb fonts by <a href="http://fonts.info/">fonts.info</a>. Thanks!</p>