<h2>Regulamin</h2>
<p>Korzystanie z serwisu Blipoteka.pl oznacza akceptację regulaminu:</p>
<ol>
<li>Sza­nuj książkę, nie niszcz jej, nie ubrudź, nie zalej — niech jak naj­wię­cej osób z niej sko­rzy­sta.
<li>Nie prze­ka­zuj dostępu do kont, doku­men­tów, haseł osobom postronnym.
<li>Czas przetrzy­mywania wynosi mie­siąc od dnia otrzy­ma­nia książki do rąk.</li>
<li>Nie przekazuj książki oznaczonej <q>wróć</q> innej osobie bez konsultacji z jej właścicielem.</li>
<li>…</li>
</ol>
