<header>
	<h2>403 Brak dostępu</h2>
</header>
<section class="body">
	<p>Strona, do której próbowano uzyskać dostęp, wymaga <a href="<?php echo $this->url(array(), 'index'); ?>">zalogowania</a>.</p>
	<p>Nie masz jeszcze konta w Blipotece? <a href="<?php echo $this->url(array(), 'signup'); ?>">Zarejestruj się</a>, zajmie Ci to nie dłużej niż minutę!</p>
	<p>Jesteś zalogowany(-a), ale widzisz ten komunikat? <a href="<?php echo $this->url(array(), 'contact'); ?>">Napisz do nas</a> koniecznie, bo to pewnie jakiś błąd.</p>
</section>