<header>
	<h2>404 Brak strony</h2>
</header>
<section class="body">
	<p>Strona o takim adresie nie istnieje, przykro nam! Spróbuj:</p>
	<ul>
		<li>przejść do <a href="<?php echo $this->url(array(), 'index'); ?>">strony głównej</a> Blipoteki</li>
		<li>odwiedzić i skomentować naszego <a href="<?php echo $this->url(array(), 'blog'); ?>">bloga</a></li>
		<li>zaparzyć sobie herbaty i coś poczytać...</li>
	</ul>
	<p>Uważasz, że ta strona powinna tu być? <a href="<?php echo $this->url(array(), 'contact'); ?>">Napisz do nas</a>!</p>
</section>
