<?php echo $this->doctype() . "\n"; ?>
<?php echo $this->html5BoilerplateHtml($this->lang, false); ?>
<head>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headLink() . "\n"; ?>
<script src="<?php echo $this->baseUrl("js/libs/modernizr-1.6.min.js"); ?>"></script>
<?php echo $this->inlineScript()->setScript(sprintf("var baseUrl = '%s';", $this->baseUrl(''))); ?>
</head>
<body>
<div id="wrap">
	<div id="container">
		<section id="header">
			<div class="container_12 clearfix">
				<header class="grid_12">
					<h1>Blipoteka.pl</h1>
					<p>Mię­dzy­mia­stowa biblioteka użyt­kow­ni­ków ser­wisu Blip.pl</p>
				</header>
			</div>
		</section>
		<section id="content" class="container_12 content">
			<div class="grid_12">
			<?php echo $this->layout()->content . "\n" ?>
			</div>
		</section>
	</div>
</div>

<?php echo $this->partial('footer-layout.phtml') . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<?php echo $this->partial('footer.phtml') . "\n"; ?>
</body>
</html>