<h2>Autor: <?php echo $this->author['name']; ?></h2>

<?php $count = count($this->books); ?>

<?php if ($count > 0): ?>
<p class="top-nav-link">&laquo; <a href="<?php echo $this->previousPage('book-index'); ?>">wróć do listy książek</a></p>
<?php echo $this->partial('book-count.phtml', array('count' => $count)); ?>
<?php foreach ($this->books as $book): ?>
<?php echo $this->partial('book-list-element.phtml', array('book' => $book)); ?>
<?php endforeach; ?>
<?php else: ?>
<p>Nie znaleziono żadnych książek tego autora. <a href="<?php echo $this->url(array(), 'index'); ?>">Dodaj jakąś</a>, jeśli ją posiadasz.</p>
<?php endif; ?>

<p class="top-nav-link">&laquo; <a href="<?php echo $this->previousPage('book-index'); ?>">wróć do listy książek</a></p>
