<?php $pagination = $this->paginationControl($this->books, 'Sliding', 'paginators/book-list.phtml'); ?>
<h2>Wszystkie książki</h2>
<?php echo $this->partial('book-count.phtml', array('count' => $this->books->getTotalItemCount())); ?>
<section class="book-list">
	<?php echo $pagination; ?>
	<?php foreach ($this->books as $book): ?>
	<?php echo $this->partial('book-list-element.phtml', array('book' => $book)); ?>
	<?php endforeach; ?>
	<?php echo $pagination; ?>
</section>
